# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'simulacion.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Simulacion(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(684, 485)
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(350, 20, 321, 221))
        self.groupBox.setObjectName("groupBox")
        self.gridLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 40, 301, 171))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.cant_elevadores_utilizados_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.cant_elevadores_utilizados_label.setAlignment(QtCore.Qt.AlignCenter)
        self.cant_elevadores_utilizados_label.setObjectName("cant_elevadores_utilizados_label")
        self.gridLayout.addWidget(self.cant_elevadores_utilizados_label, 3, 0, 1, 1)
        self.cant_mecanicos_utilizados_val_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.cant_mecanicos_utilizados_val_label.setAlignment(QtCore.Qt.AlignCenter)
        self.cant_mecanicos_utilizados_val_label.setObjectName("cant_mecanicos_utilizados_val_label")
        self.gridLayout.addWidget(self.cant_mecanicos_utilizados_val_label, 1, 1, 1, 1)
        self.cant_elevadores_utilizados_val_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.cant_elevadores_utilizados_val_label.setAlignment(QtCore.Qt.AlignCenter)
        self.cant_elevadores_utilizados_val_label.setObjectName("cant_elevadores_utilizados_val_label")
        self.gridLayout.addWidget(self.cant_elevadores_utilizados_val_label, 3, 1, 1, 1)
        self.cant_mecanicos_utilizados_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.cant_mecanicos_utilizados_label.setAlignment(QtCore.Qt.AlignCenter)
        self.cant_mecanicos_utilizados_label.setObjectName("cant_mecanicos_utilizados_label")
        self.gridLayout.addWidget(self.cant_mecanicos_utilizados_label, 1, 0, 1, 1)
        self.cant_mecanicos_libres_val_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.cant_mecanicos_libres_val_label.setAlignment(QtCore.Qt.AlignCenter)
        self.cant_mecanicos_libres_val_label.setObjectName("cant_mecanicos_libres_val_label")
        self.gridLayout.addWidget(self.cant_mecanicos_libres_val_label, 2, 1, 1, 1)
        self.cant_autos_galpon_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.cant_autos_galpon_label.setAlignment(QtCore.Qt.AlignCenter)
        self.cant_autos_galpon_label.setObjectName("cant_autos_galpon_label")
        self.gridLayout.addWidget(self.cant_autos_galpon_label, 0, 0, 1, 1)
        self.cant_autos_galpon_val_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.cant_autos_galpon_val_label.setAlignment(QtCore.Qt.AlignCenter)
        self.cant_autos_galpon_val_label.setObjectName("cant_autos_galpon_val_label")
        self.gridLayout.addWidget(self.cant_autos_galpon_val_label, 0, 1, 1, 1)
        self.cant_mecanicos_libres_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.cant_mecanicos_libres_label.setAlignment(QtCore.Qt.AlignCenter)
        self.cant_mecanicos_libres_label.setObjectName("cant_mecanicos_libres_label")
        self.gridLayout.addWidget(self.cant_mecanicos_libres_label, 2, 0, 1, 1)
        self.cant_elevadores_libres_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.cant_elevadores_libres_label.setAlignment(QtCore.Qt.AlignCenter)
        self.cant_elevadores_libres_label.setObjectName("cant_elevadores_libres_label")
        self.gridLayout.addWidget(self.cant_elevadores_libres_label, 4, 0, 1, 1)
        self.cant_elevadores_libres_val_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.cant_elevadores_libres_val_label.setAlignment(QtCore.Qt.AlignCenter)
        self.cant_elevadores_libres_val_label.setObjectName("cant_elevadores_libres_val_label")
        self.gridLayout.addWidget(self.cant_elevadores_libres_val_label, 4, 1, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 260, 321, 221))
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.groupBox_2)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 40, 301, 171))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.cant_autos_reparados_val_label = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.cant_autos_reparados_val_label.setAlignment(QtCore.Qt.AlignCenter)
        self.cant_autos_reparados_val_label.setObjectName("cant_autos_reparados_val_label")
        self.gridLayout_2.addWidget(self.cant_autos_reparados_val_label, 1, 1, 1, 1)
        self.sin_elevador_val_label = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.sin_elevador_val_label.setAlignment(QtCore.Qt.AlignCenter)
        self.sin_elevador_val_label.setObjectName("sin_elevador_val_label")
        self.gridLayout_2.addWidget(self.sin_elevador_val_label, 3, 1, 1, 1)
        self.cant_autos_reparados_label = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.cant_autos_reparados_label.setAlignment(QtCore.Qt.AlignCenter)
        self.cant_autos_reparados_label.setObjectName("cant_autos_reparados_label")
        self.gridLayout_2.addWidget(self.cant_autos_reparados_label, 1, 0, 1, 1)
        self.con_elevador_val_label = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.con_elevador_val_label.setAlignment(QtCore.Qt.AlignCenter)
        self.con_elevador_val_label.setObjectName("con_elevador_val_label")
        self.gridLayout_2.addWidget(self.con_elevador_val_label, 2, 1, 1, 1)
        self.cant_dias_transcurridos_label = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.cant_dias_transcurridos_label.setAlignment(QtCore.Qt.AlignCenter)
        self.cant_dias_transcurridos_label.setObjectName("cant_dias_transcurridos_label")
        self.gridLayout_2.addWidget(self.cant_dias_transcurridos_label, 0, 0, 1, 1)
        self.cant_dias_transcurridos_val_label = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.cant_dias_transcurridos_val_label.setAlignment(QtCore.Qt.AlignCenter)
        self.cant_dias_transcurridos_val_label.setObjectName("cant_dias_transcurridos_val_label")
        self.gridLayout_2.addWidget(self.cant_dias_transcurridos_val_label, 0, 1, 1, 1)
        self.con_elevador_label = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.con_elevador_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.con_elevador_label.setObjectName("con_elevador_label")
        self.gridLayout_2.addWidget(self.con_elevador_label, 2, 0, 1, 1)
        self.cant_autos_rechazados_label = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.cant_autos_rechazados_label.setAlignment(QtCore.Qt.AlignCenter)
        self.cant_autos_rechazados_label.setObjectName("cant_autos_rechazados_label")
        self.gridLayout_2.addWidget(self.cant_autos_rechazados_label, 4, 0, 1, 1)
        self.cant_autos_rechazados_val_label = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.cant_autos_rechazados_val_label.setAlignment(QtCore.Qt.AlignCenter)
        self.cant_autos_rechazados_val_label.setObjectName("cant_autos_rechazados_val_label")
        self.gridLayout_2.addWidget(self.cant_autos_rechazados_val_label, 4, 1, 1, 1)
        self.sin_elevador_label = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.sin_elevador_label.setObjectName("sin_elevador_label")
        self.gridLayout_2.addWidget(self.sin_elevador_label, 3, 0, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 20, 321, 221))
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.groupBox_3)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(10, 40, 301, 171))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.cant_mecanicos_val_label = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.cant_mecanicos_val_label.setAlignment(QtCore.Qt.AlignCenter)
        self.cant_mecanicos_val_label.setObjectName("cant_mecanicos_val_label")
        self.gridLayout_3.addWidget(self.cant_mecanicos_val_label, 1, 1, 1, 1)
        self.cant_mecanicos_label = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.cant_mecanicos_label.setAlignment(QtCore.Qt.AlignCenter)
        self.cant_mecanicos_label.setObjectName("cant_mecanicos_label")
        self.gridLayout_3.addWidget(self.cant_mecanicos_label, 1, 0, 1, 1)
        self.cant_elevadores_val_label = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.cant_elevadores_val_label.setAlignment(QtCore.Qt.AlignCenter)
        self.cant_elevadores_val_label.setObjectName("cant_elevadores_val_label")
        self.gridLayout_3.addWidget(self.cant_elevadores_val_label, 2, 1, 1, 1)
        self.dias_simulacion_label = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.dias_simulacion_label.setAlignment(QtCore.Qt.AlignCenter)
        self.dias_simulacion_label.setObjectName("dias_simulacion_label")
        self.gridLayout_3.addWidget(self.dias_simulacion_label, 0, 0, 1, 1)
        self.dias_simulacion_val_label = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.dias_simulacion_val_label.setAlignment(QtCore.Qt.AlignCenter)
        self.dias_simulacion_val_label.setObjectName("dias_simulacion_val_label")
        self.gridLayout_3.addWidget(self.dias_simulacion_val_label, 0, 1, 1, 1)
        self.cant_elevadores_label = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.cant_elevadores_label.setAlignment(QtCore.Qt.AlignCenter)
        self.cant_elevadores_label.setObjectName("cant_elevadores_label")
        self.gridLayout_3.addWidget(self.cant_elevadores_label, 2, 0, 1, 1)
        self.gridLayoutWidget_4 = QtWidgets.QWidget(Dialog)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(350, 330, 321, 141))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.ver_grafico_uno_button = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.ver_grafico_uno_button.setObjectName("ver_grafico_uno_button")
        self.gridLayout_4.addWidget(self.ver_grafico_uno_button, 2, 0, 1, 1)
        self.ver_grafico_tres_button = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.ver_grafico_tres_button.setObjectName("ver_grafico_tres_button")
        self.gridLayout_4.addWidget(self.ver_grafico_tres_button, 4, 0, 1, 1)
        self.ver_grafico_dos_button = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.ver_grafico_dos_button.setObjectName("ver_grafico_dos_button")
        self.gridLayout_4.addWidget(self.ver_grafico_dos_button, 3, 0, 1, 1)
        self.lcdNumber = QtWidgets.QLCDNumber(Dialog)
        self.lcdNumber.setGeometry(QtCore.QRect(340, 250, 151, 71))
        self.lcdNumber.setObjectName("lcdNumber")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(500, 260, 151, 51))
        self.label.setTextFormat(QtCore.Qt.PlainText)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Simulación de un Taller Mecánico"))
        Dialog.setWindowIcon(QtGui.QIcon('car.png'))
        self.groupBox.setTitle(_translate("Dialog", "Estado del Sistema"))
        self.cant_elevadores_utilizados_label.setText(_translate("Dialog", "Cantidad de Elevadores utilizados"))
        self.cant_mecanicos_utilizados_val_label.setText(_translate("Dialog", "3"))
        self.cant_elevadores_utilizados_val_label.setText(_translate("Dialog", "2"))
        self.cant_mecanicos_utilizados_label.setText(_translate("Dialog", "Cantidad de Mecanicos utilizados"))
        self.cant_mecanicos_libres_val_label.setText(_translate("Dialog", "0"))
        self.cant_autos_galpon_label.setText(_translate("Dialog", "Cantidad de Autos en el galpón"))
        self.cant_autos_galpon_val_label.setText(_translate("Dialog", "5"))
        self.cant_mecanicos_libres_label.setText(_translate("Dialog", "Cantidad de Mecanicos libres"))
        self.cant_elevadores_libres_label.setText(_translate("Dialog", "Cantidad de Elevadores libres"))
        self.cant_elevadores_libres_val_label.setText(_translate("Dialog", "1"))
        self.groupBox_2.setTitle(_translate("Dialog", "Datos Generales"))
        self.cant_autos_reparados_val_label.setText(_translate("Dialog", "23"))
        self.sin_elevador_val_label.setText(_translate("Dialog", "2"))
        self.cant_autos_reparados_label.setText(_translate("Dialog", "Cantidad de Autos reparados"))
        self.con_elevador_val_label.setText(_translate("Dialog", "232"))
        self.cant_dias_transcurridos_label.setText(_translate("Dialog", "Cantidad de días transcurridos"))
        self.cant_dias_transcurridos_val_label.setText(_translate("Dialog", "13"))
        self.con_elevador_label.setText(_translate("Dialog", "+ Con Elevador"))
        self.cant_autos_rechazados_label.setText(_translate("Dialog", "Cantidad de Autos Rechazados"))
        self.cant_autos_rechazados_val_label.setText(_translate("Dialog", "1"))
        self.sin_elevador_label.setText(_translate("Dialog", "+ Sin Elevador"))
        self.groupBox_3.setTitle(_translate("Dialog", "Datos de Entrada"))
        self.cant_mecanicos_val_label.setText(_translate("Dialog", "3"))
        self.cant_mecanicos_label.setText(_translate("Dialog", "Cantidad de Mecánicos"))
        self.cant_elevadores_val_label.setText(_translate("Dialog", "3"))
        self.dias_simulacion_label.setText(_translate("Dialog", "Días de Simulación"))
        self.dias_simulacion_val_label.setText(_translate("Dialog", "30"))
        self.cant_elevadores_label.setText(_translate("Dialog", "Cantidad de Elevadores"))
        self.ver_grafico_uno_button.setText(_translate("Dialog", "Ver Grafico 1"))
        self.ver_grafico_tres_button.setText(_translate("Dialog", "Ver Grafico 3"))
        self.ver_grafico_dos_button.setText(_translate("Dialog", "Ver Grafico 2"))
        self.label.setText(_translate("Dialog", "Dias Transcurridos"))

